import { getFlattenPermissions } from "@/utils";
const permissions = [
  {
    description: "权限1",
    id: 1,
    is_show: true,
    key: "key1",
    level: "1",
    name: "权限1",
    parent_id: 0,
    parent_key: "",
    permissions: [
      {
        created_at: 1,
        description: "权限1-1",
        id: 11,
        key: "key1-1",
        level: "2",
        name: "权限1-1",
        ternary_type: "1",
        updated_at: 1,
      },
      {
        created_at: 1,
        description: "权限1-2",
        id: 12,
        key: "key1-2",
        level: "2",
        name: "权限1-2",
        ternary_type: "1",
        updated_at: 1,
      },
    ],
    sort: 1,
    sub_menu: [
      {
        description: "权限1-1",
        id: 11,
        is_show: true,
        key: "key1-1",
        level: "2",
        name: "权限1-1",
        parent_id: 1,
        parent_key: "key1",
        permissions: [],
        sort: 1,
        sub_menu: [
          {
            description: "权限1-1-1",
            id: 111,
            is_show: true,
            key: "key1-1-1",
            level: "3",
            name: "权限1-1-1",
            parent_id: 11,
            parent_key: "key1-1",
            permissions: [],
            sort: 1,
            sub_menu: [
              {
                description: "权限1-1-1-1",
                id: 1111,
                is_show: true,
                key: "key1-1-1-1",
                level: "4",
                name: "权限1-1-1-1",
                parent_id: 111,
                parent_key: "key1-1-1",
                permissions: [],
                sort: 1,
                sub_menu: [
                  {
                    description: "权限1-1-1-1-1",
                    id: 11111,
                    is_show: true,
                    key: "key1-1-1-1-1",
                    level: "5",
                    name: "权限1-1-1-1-1",
                    parent_id: 1111,
                    parent_key: "key1-1-1-1",
                    permissions: [],
                    sort: 1,
                    sub_menu: [],
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        description: "权限1-2",
        id: 12,
        is_show: true,
        key: "key1-2",
        level: "2",
        name: "权限1-2",
        parent_id: 1,
        parent_key: "key1",
        permissions: [],
        sort: 2,
        sub_menu: [],
      },
    ],
  },
  {
    description: "权限2",
    id: 2,
    is_show: true,
    key: "key2",
    level: "1",
    name: "权限2",
    parent_id: 0,
    parent_key: "",
    permissions: [
      {
        created_at: 1,
        description: "权限2-1",
        id: 21,
        key: "key2-1",
        level: "2",
        name: "权限2-1",
        ternary_type: "1",
        updated_at: 1,
      },
      {
        created_at: 1,
        description: "权限2-2",
        id: 22,
        key: "key2-2",
        level: "2",
        name: "权限2-2",
        ternary_type: "1",
        updated_at: 1,
      },
    ],
    sort: 2,
    sub_menu: [
      {
        description: "权限2-1",
        id: 21,
        is_show: true,
        key: "key2-1",
        level: "2",
        name: "权限2-1",
        parent_id: 2,
        parent_key: "key2",
        permissions: [],
        sort: 1,
        sub_menu: [],
      },
      {
        description: "权限2-2",
        id: 22,
        is_show: true,
        key: "key2-2",
        level: "2",
        name: "权限2-2",
        parent_id: 2,
        parent_key: "key2",
        permissions: [],
        sort: 2,
        sub_menu: [],
      },
    ],
  },
];
describe("获取扁平化权限", () => {
  test("正常情况", () => {
    expect(getFlattenPermissions(permissions)).toEqual([
      "key1",
      "key1-1",
      "key1-1-1",
      "key1-1-1-1",
      "key1-2",
      "key2",
      "key2-1",
      "key2-2",
    ]);
  });
  test("isShow为false情况", () => {
    expect(getFlattenPermissions([{ ...permissions[0], is_show: false }])).toEqual([]);
  });
});
